#ifndef _WITLEAFPROTOCOL_H_
#define _WITLEAFPROTOCOL_H_

#include "Datatype.h"
#define COMM_IN_BUFF_LEN	0xFF
#define COMM_OUT_BUFF_LEN	0x0D48

#define WITLEAF_UART_RX_BUFF_LEN		1024
#define WITLEAF_MIN_FRAME_LEN		10
#define WITLEAF_MAX_FRAME_DATA_LEN	36
#define WITLEAF_MAX_FRAME_CACHE_LEN	100

#define WITLEAF_PACKET_HEAD	0xFA
#define ENABLE_USART1
//#define MOBILEPHONE
#define WITLEAF_UART_BUFF_LEN		1024
typedef struct _WITLEAF_UARTCOMM
{
	unsigned char pu8Buff[WITLEAF_UART_BUFF_LEN];				    // 串口数据接收缓冲区
	unsigned int u32WriteIndex;                   					// 串口数据接收缓冲区写入数据下标
	unsigned int u32ReadIndex;                    					// 串口数据接收缓冲区读出数据下标     
} WITLEAF_UARTCOMM;

typedef enum _WITLEAF_SEARCH_PACKET_STATUS_LIST
{
	WITLEAF_SEARCH_PACKET_STATUS_HEAD,
	WITLEAF_SEARCH_PACKET_STATUS_LEN,
	WITLEAF_SEARCH_PACKET_STATUS_PARA_TYPE,
	WITLEAF_SEARCH_PACKET_STATUS_TYPE,
	WITLEAF_SEARCH_PACKET_STATUS_ID,
	WITLEAF_SEARCH_PACKET_STATUS_NO_0,
	WITLEAF_SEARCH_PACKET_STATUS_NO_1,
	WITLEAF_SEARCH_PACKET_STATUS_NO_2,
	WITLEAF_SEARCH_PACKET_STATUS_NO_3,
	WITLEAF_SEARCH_PACKET_STATUS_DATA,	
	WITLEAF_SEARCH_PACKET_STATUS_CHECKSUM,

	WITLEAF_SEARCH_PACKET_STATUS_MAX
} WITLEAF_SEARCH_PACKET_STATUS_LIST;

typedef struct _WITLEAF_PACKET
{
	UINT8 u8Len;
	UINT8 u8ParaType;
	UINT8 u8Type;
	UINT8 u8Id;
	UINT32 u32No;
	UINT8 pu8Data[WITLEAF_MAX_FRAME_DATA_LEN];
	UINT8 u8Checksum;
} WITLEAF_PACKET;

typedef enum _WITLEAF_MODULE_LIST
{
	WITLEAF_MODULE_ECG	= 0x01,
	WITLEAF_MODULE_SPO2 = 0x03,
	WITLEAF_MODULE_RESP = 0x15,
} WITLEAF_MODULE_LIST;
 
typedef enum _WITLEAF_PACKET_TYPE_LIST
{	
	WITLEAF_PACKET_TYPE_DC = 0x01,
	WITLEAF_PACKET_TYPE_DR = 0x02,
	WITLEAF_PACKET_TYPE_DA = 0x03,
	WITLEAF_PACKET_TYPE_DD = 0x04,

	WITLEAF_PACKET_TYPE_MAX
} WITLEAF_PACKET_TYPE_LIST;

typedef enum _WITLEAF_CMD_LIST
{
	WITLEAF_CMD_NONE					= 0x00,
	WITLEAF_CMD_POWERON_HAND=0X01,
	WITLEAF_CMD_SET_PATIENT_MODE		= 0x10,
	WITLEAF_CMD_SET_LEAD_MODE	= 0x20,
	WITLEAF_CMD_SET_LEAD_CHANNEL	= 0x21,
	WITLEAF_CMD_SET_FILTER_MODE			= 0x22,
	WITLEAF_CMD_SET_50HZ_60HZ_FILTER	= 0x23,
	WITLEAF_CMD_SET_ECG_GAIN		= 0x24,
	WITLEAF_CMD_SET_ST_PLATE	= 0x25,
	WITLEAF_CMD_SET_HEART_CAL_CHANNEL		= 0x26,
	WITLEAF_CMD_START_OR_STOP_PACE			= 0x27,	
	WITLEAF_CMD_START_ECG_CALIBRATE			= 0x28,
	WITLEAF_CMD_SLEEP				= 0x31,
	WITLEAF_CMD_SET_CUFFPRS_PARA		= 0x70,
	WITLEAF_CMD_SET_SECURITY		= 0x71,
	WITLEAF_CMD_UPDATE				= 0x7F,
	WITLEAF_CMD_MAX
} WITLEAF_CMD_LIST;

typedef enum _WITLEAF_RESPONSE_LIST
{
	WITLEAF_RESPONSE_ANSWER			= 0x80,
	WITLEAF_POWERON_HAND_REQUEST= 0x81,
	WITLEAF_RESPONSE_MODULE_INFO		= 0x82,
	WITLEAF_SPO2_DATA = 0x83,
	WITLEAF_ECG_WAVE_DATA		= 0x90,
	WITLEAF_ECG_LEAD_STATUS		= 0x92,
	WITLEAF_RESPONSE_PACE_STATUS	= 0x93,
	
	WITLEAF_RESPONSE_MAX
} WITLEAF_RESPONSE_LIST;

typedef enum _WITLEAF_RCV_CMD_RESULT_LIST
{
	WITLEAF_RCV_CMD_RESULT_NORMAL			= 0x00,
	WITLEAF_RCV_CMD_RESULT_MODULE_ERROR		= 0x01,
	WITLEAF_RCV_CMD_RESULT_TYPE_ERROR		= 0x02,
	WITLEAF_RCV_CMD_RESULT_ID_ERROR			= 0x03,
	WITLEAF_RCV_CMD_RESULT_PARA_ERROR		= 0x04,
	WITLEAF_RCV_CMD_RESULT_NO_ERROR			= 0x05,
	WITLEAF_RCV_CMD_RESULT_CHECKSUM_ERROR			= 0x06,
	WITLEAF_EXECUTE_CMD_RESULT_SUCCESS			= 0x07,
	WITLEAF_EXECUTE_CMD_RESULT_FAIL			= 0x08,
	WITLEAF_EXECUTE_CMD_RESULT_BUSY			= 0x09,

	WITLEAF_RCV_CMD_RESULT_MAX
} WITLEAF_RCV_CMD_RESULT_LIST;


extern WITLEAF_UARTCOMM gtWitleafComm;
#endif
